name: R-CMD-check

on: [push, pull_request]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Set environment variables
      run: |
        echo "R_LIBS_USER=/__w/_temp/Library" >> $GITHUB_ENV
        echo "TZ=UTC" >> $GITHUB_ENV
        echo "_R_CHECK_SYSTEM_CLOCK_=FALSE" >> $GITHUB_ENV
        echo "NOT_CRAN=true" >> $GITHUB_ENV

    - name: Restore R package dependencies
      run: R -e 'renv::restore()'

    - name: Install devtools
      run: |
        renv::install('devtools')
      shell: Rscript {0}

    - name: Install the package
      run: R CMD INSTALL .

    - name: Run tests
      run: R -e 'devtools::test()'
