name: R-CMD-check

on: [push, pull_request]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install remotes and renv
      run: |
        install.packages('remotes')
        install.packages('renv')

    - name: Restore R package dependencies
      run: R -e 'renv::restore()'

    - name: Install the package
      run: R CMD INSTALL .

    - name: Run tests
      run: R -e 'devtools::test()'
